Web client
Monitoring-of-individuals/backend-monitoring pull request #12
Opened 2024-03-07 20:01 UTC by Brill1983

К рассмотрению клиент ApiCloudClient для получения данных от поставщиков. 
Методы слоя service, model, controller а так же ReportBuilder пока носят больше демонстрационную и связующую функцию. Их в будущем необходимо заполнить логикой и расширить функционал.

2024-03-11 09:11 UTC, nkorzh requested changes

2024-03-12 10:27 UTC, Brill1983 commented on src/main/java/ru/monitoring/controllers/ReportController.java
> +        String passportNomer = "567890";
Исправил.

2024-03-12 10:27 UTC, Brill1983 commented on src/main/java/ru/monitoring/dto/nalog/SelfEmplResponse.java
> +    private int NPD; // Статус НПД (1 - является налогоплательщиком на профессиональный доход, 0 - не является)
Исправил.

2024-03-12 10:32 UTC, Brill1983 commented on src/main/java/ru/monitoring/dto/gibdd/Deprivation.java
> +    private String fis_id;
Исправил. Внедрил библиотеку fastjson. Отличные возможности. В связи с этим сильно упростил клиента - теперь там один универсальный метод, возвращающий строку с JSON или null в случае 4хх или 5хх ошибки.
В свою очередь, в приватные методы сервиса, которые формируют параметры запросы, добавил проверку на возвращаемый null, и, в случае ответа в сиде строки JSON, там же осуществляется парсинг в объект нужного класса. А в случае если клиент возвращает null, то приватный метод возвращает пустой объект соответствующего класса.

2024-03-12 10:33 UTC, Brill1983 commented on src/main/java/ru/monitoring/exceptions/ClentError4xxException.java
> +public class ClentError4xxException extends RuntimeException {
Исправил.

2024-03-12 10:33 UTC, Brill1983 commented on src/main/java/ru/monitoring/service/SupplierRequestService.java
> +    public Report getReport(String lastname, String firstname, String secondname, String birthdate, String passportSeria,
Исправил

2024-03-12 10:37 UTC, Brill1983 commented on src/main/java/ru/monitoring/service/SupplierRequestService.java
> +    public Report getReport(String lastname, String firstname, String secondname, String birthdate, String passportSeria,
Сделал PersonalInfoDto. Логику получения получения ИНН и склейки серии и номера перенес в приватные соответствующие методы.

2024-03-12 10:38 UTC, Brill1983 commented on src/main/java/ru/monitoring/service/SupplierRequestService.java
> +        return apiCloudClient.getSelfEmplByInn("/nalog.php", paramMap);
После ряда исправлений должно быть, что если какой-то вызов ответил ошибкой, остальные вызовы отработают.

2024-03-14 12:07 UTC, merged